/// <reference types="react-native" />
import * as React from 'react';
import { IProps, IState } from './Options';
export default class Modalize extends React.Component<IProps, IState> {
    static defaultProps: {
        handlePosition: string;
        useNativeDriver: boolean;
        adjustToContentHeight: boolean;
        withReactModal: boolean;
        withHandle: boolean;
    };
    private snaps;
    private snapEnd;
    private beginScrollYValue;
    private contentAlreadyCalculated;
    private beginScrollY;
    private dragY;
    private translateY;
    private reverseBeginScrollY;
    private modal;
    private modalChildren;
    private modalContentView;
    private contentView;
    private modalOverlay;
    private modalOverlayTap;
    private willCloseModalize;
    constructor(props: IProps);
    componentDidMount(): void;
    open: () => void;
    close: () => void;
    scrollTo: (y?: number | {
        x?: number | undefined;
        y?: number | undefined;
        animated?: boolean | undefined;
    } | undefined, x?: number | undefined, animated?: boolean | undefined) => void;
    private readonly isIos;
    private readonly isIphoneX;
    private readonly isHandleOutside;
    private readonly handleHeight;
    private readonly modalizeContent;
    private readonly overlayBackground;
    private isAbsolute;
    private onAnimateOpen;
    private onAnimateClose;
    private onContentViewLayout;
    private onContentViewChange;
    private onHandleComponent;
    private onHandleChildren;
    private onHandleOverlay;
    private onBackPress;
    private onKeyboardShow;
    private onKeyboardHide;
    private renderComponent;
    private renderHandle;
    private renderHeader;
    private renderContent;
    private renderChildren;
    private renderFooter;
    private renderOverlay;
    private renderModalize;
    private renderReactModal;
    render(): React.ReactNode;
}
